{% set name = "amrex" %}
{% set version = "25.04" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}
{% set mpi_prefix = "nompi" if mpi == "nompi" else "mpi_" + mpi %}
{% set build_number = build + 100 if mpi == "nompi" else build %}
{% set build_string = mpi_prefix + "_h{{ PKG_HASH }}_" + build_number|string %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AMReX-Codes/amrex/archive/refs/tags/{{ version }}.tar.gz
  sha256: 70f1cbbee2fb1f699f6bc906902f19e6f4cdbf21eb2df92d1dcb75926defb192

build:
  number: {{ build_number }}
  string: {{ build_string }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make                # [unix]
    - clang               # [win]
    - lld                 # [win]
    - llvm-openmp         # [win or osx]
    - ninja               # [win]
    - libgomp             # [linux]
    - openmpi             # [(mpi == "openmpi") and (build_platform != target_platform)]
  host:
    - {{ mpi }}           # [mpi != "nompi"]
    - fftw
  run:
    - {{ mpi }}           # [mpi != "nompi"]
    - libcxx              # [osx]
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
    - amrex =={{ version }}

test:
  commands:
    - test -f $PREFIX/include/AMReX.H
    - test -f $PREFIX/{{ "lib" if unix else "Library" }}/cmake/{{ "AMReX/" if unix else "" }}AMReXConfig.cmake

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A software framework for massively parallel, block-structured adaptive mesh refinement (AMR) applications
  description: |
    AMReX is a software framework containing all the functionality to write
    massively parallel, block-structured adaptive mesh refinement (AMR)
    applications. AMReX is an Established Project of the High Performance Software Foundation.
  home: https://amrex-codes.github.io/amrex/
  dev_url: https://github.com/AMReX-Codes/amrex
  doc_url: https://amrex-codes.github.io/amrex/docs_html/

extra:
  recipe-maintainers:
    - atmyers
    - ax3l
    - WeiqunZhang
